name: tiara_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rounded_progress_bar: 0.1.1
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  hive: ^1.1.1
  hive_flutter: ^0.2.1
  kernel: ^0.3.26
  front_end: ^0.1.25
  json_annotation: ^3.0.1
  moor: ^2.4.0
  moor_flutter: ^2.1.1
  path_provider:
  path:
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.3
  flutter_staggered_grid_view: ^0.3.0
  expandable: ^4.0.1
  grouped_buttons: ^1.0.4
  flutter_money_formatter: ^0.8.3
  provider: ^4.0.1
  percent_indicator: "^2.1.1"
  flutter_tags: ^0.4.5
  carousel_slider: ^1.4.1
  cached_network_image: ^2.0.0
  analyzer: ^0.39.4
  recase: ^3.0.0
  intl: ^0.15.8
  connectivity: ^0.4.8+1
  quiver: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.2
  moor_generator: ^2.2.0
  build_runner:
  json_serializable: ^3.2.2

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/background/
    - assets/banners/
    - assets/bottomNavIcons/
    - assets/fonts/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/logo/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
